name: OCI Compute Instance Run

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-oci-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create Configuration and Key Files
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ./private.pem
          chmod 600 ./private.pem
          echo "OCI_REGION=${{ secrets.OCI_REGION }}" > .env
          echo "OCI_USER_ID=${{ secrets.OCI_USER_ID }}" >> .env
          echo "OCI_TENANCY_ID=${{ secrets.OCI_TENANCY_ID }}" >> .env
          echo "OCI_KEY_FINGERPRINT=${{ secrets.OCI_KEY_FINGERPRINT }}" >> .env
          echo "OCI_PRIVATE_KEY_FILENAME=./private.pem" >> .env
          echo "OCI_SUBNET_ID=${{ secrets.OCI_SUBNET_ID }}" >> .env
          echo "OCI_IMAGE_ID=${{ secrets.OCI_IMAGE_ID }}" >> .env
          echo "OCI_OCPUS=${{ secrets.OCI_OCPUS }}" >> .env
          echo "OCI_MEMORY_IN_GBS=${{ secrets.OCI_MEMORY_IN_GBS }}" >> .env
          echo "OCI_SHAPE=${{ secrets.OCI_SHAPE }}" >> .env

      - name: Execute API Request
        run: php index.php
